import SwiftUI
import PhotosUI
import UIKit

struct OnboardingView: View {
    @EnvironmentObject private var session: SessionStore; @State private var age = ""; @State private var goal = "Больше энергии"; @State private var units = "metric"; @State private var saving = false
    var body: some View { NavigationStack { Form { Section("Ваш профиль") { TextField("Возраст", text: $age).keyboardType(.numberPad); Picker("Цель", selection: $goal) { Text("Больше энергии").tag("Больше энергии"); Text("Сбалансированное питание").tag("Сбалансированное питание"); Text("Больше активности").tag("Больше активности") }; Picker("Единицы", selection: $units) { Text("Metric").tag("metric"); Text("Imperial").tag("imperial") } }; Button(saving ? "Сохраняем…" : "Продолжить") { Task { saving = true; defer { saving = false }; if let value = Int(age) { do { let response: UserResponse = try await session.api.request("/profile", method: "PATCH", body: OnboardingBody(age: value, goal: goal, units: units)); session.user = response.user } catch { } } } }.disabled(Int(age) == nil || saving) }.navigationTitle("Настройка FITLY") } }
}
private struct OnboardingBody: Encodable { let age: Int; let goal: String; let units: String }

struct FoodScannerView: View {
    @EnvironmentObject private var session: SessionStore; @State private var picker: PhotosPickerItem?; @State private var imageData: Data?; @State private var result: ScanResult?; @State private var loading = false; @State private var camera = false; @State private var error: String?
    var body: some View { ScrollView { VStack(spacing: 16) { if let imageData, let image = UIImage(data: imageData) { Image(uiImage: image).resizable().scaledToFit().clipShape(RoundedRectangle(cornerRadius: 18)); Button("Распознать") { Task { await analyze(imageData) } }.buttonStyle(.borderedProminent).tint(.green) } else { VStack(spacing: 8) { Image(systemName: "camera.viewfinder").font(.largeTitle); Text("Выберите фото или сделайте снимок").foregroundStyle(.secondary) }.frame(maxWidth: .infinity).padding(40) }; HStack { PhotosPicker("Галерея", selection: $picker, matching: .images); Button("Камера") { camera = true }.disabled(!UIImagePickerController.isSourceTypeAvailable(.camera)) }; if loading { ProgressView("Анализируем…") }; if let result { VStack(alignment: .leading, spacing: 8) { Text(result.name).font(.title3.bold()); Text("Порция: \(result.portion)"); Text("\(Int(result.calories)) ккал · Б \(Int(result.protein)) г · Ж \(Int(result.fat)) г · У \(Int(result.carbs)) г"); Text("Оценка приблизительная. Проверьте результат перед добавлением.").font(.caption).foregroundStyle(.secondary); Button("Добавить в дневник") { Task { try? await session.api.request("/meals", method: "POST", body: ScanMealBody(title: result.name, kcal: result.calories, protein: result.protein, fat: result.fat, carbs: result.carbs, fiber: result.fiber)); self.result = nil } }.buttonStyle(.borderedProminent).tint(.green) }.frame(maxWidth: .infinity, alignment: .leading).padding().background(.thinMaterial, in: RoundedRectangle(cornerRadius: 18)) }; if let error { Text(error).foregroundStyle(.red) } }.padding() }.navigationTitle("AI Food Scanner").sheet(isPresented: $camera) { CameraPicker(imageData: $imageData) }.onChange(of: picker) { item in Task { guard let item else { return }; imageData = try? await item.loadTransferable(type: Data.self) } } }
    private func analyze(_ data: Data) async { loading = true; defer { loading = false }; do { let response: ScanResponse = try await session.api.request("/ai/food-scan", method: "POST", body: ImageBody(image: "data:image/jpeg;base64,\(data.base64EncodedString())")); result = response.result } catch { error = error.localizedDescription } }
}
private struct ImageBody: Encodable { let image: String }
private struct ScanMealBody: Encodable { let title: String; let kcal: Double; let protein: Double; let fat: Double; let carbs: Double; let fiber: Double }
private struct ScanResponse: Decodable { let result: ScanResult }
private struct ScanResult: Decodable { let name: String; let portion: String; let calories: Double; let protein: Double; let fat: Double; let carbs: Double; let fiber: Double }

struct CoachView: View { @EnvironmentObject private var session: SessionStore; @State private var text = ""; @State private var messages: [String] = []; var body: some View { VStack { ScrollView { LazyVStack(alignment: .leading, spacing: 10) { ForEach(messages, id: \.self) { Text($0).padding(12).background(.thinMaterial, in: RoundedRectangle(cornerRadius: 14)) } } }.frame(maxWidth: .infinity); HStack { TextField("Спросите о своём дне", text: $text); Button { let q = text; text = ""; Task { do { let response: AIMessageResponse = try await session.api.request("/ai/coach", method: "POST", body: MessageBody(message: q)); messages.append("Вы: \(q)"); messages.append("FITLY AI: \(response.message)") } catch { messages.append(error.localizedDescription) } } } label: { Image(systemName: "arrow.up.circle.fill") } }.padding().background(.thinMaterial, in: Capsule()) }.padding().navigationTitle("FITLY AI") } }
private struct MessageBody: Encodable { let message: String }

struct PlannerView: View { @EnvironmentObject private var session: SessionStore; @State private var plans: [MealPlan] = []; var body: some View { List { ForEach(plans) { plan in Section(plan.date) { ForEach(plan.items) { item in HStack { Text(item.type.capitalized); Spacer(); Text(item.recipe?.name ?? item.food?.name ?? "Блюдо") } } } } Button("Добавить план на сегодня") { Task { try? await session.api.request("/meal-plans", method: "POST", body: PlanBody(date: ISO8601DateFormatter().string(from: Date()), type: "snack")); await load() } } }.navigationTitle("Планировщик").task { await load() }; private func load() async { plans = (try? await session.api.request("/meal-plans") as MealPlanList)?.items ?? [] } }
private struct PlanBody: Encodable { let date: String; let type: String }

struct ShoppingView: View { @EnvironmentObject private var session: SessionStore; @State private var lists: [ShoppingList] = []; @State private var newItemName = ""; var body: some View { List { ForEach(lists) { list in Section(list.name) { ForEach(list.items) { item in Button { Task { try? await session.api.request("/shopping-lists/\(list.id)/items/\(item.id)", method: "PATCH", body: PurchasedBody(purchased: !item.purchased)); await load() } } label: { Label(item.name, systemImage: item.purchased ? "checkmark.circle.fill" : "circle") } }; HStack { TextField("Название товара", text: $newItemName); Button("Добавить") { let name = newItemName.trimmingCharacters(in: .whitespacesAndNewlines); guard !name.isEmpty else { return }; Task { try? await session.api.request("/shopping-lists/\(list.id)/items", method: "POST", body: ShoppingItemBody(name: name, quantity: 1)); newItemName = ""; await load() } }.disabled(newItemName.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty) } } }; Button("Создать список") { Task { try? await session.api.request("/shopping-lists", method: "POST", body: ListBody(name: "Покупки")); await load() } } }.navigationTitle("Покупки").task { await load() }; private func load() async { lists = (try? await session.api.request("/shopping-lists") as ShoppingListResponse)?.items ?? [] } }
private struct ListBody: Encodable { let name: String }; private struct ShoppingItemBody: Encodable { let name: String; let quantity: Double }; private struct PurchasedBody: Encodable { let purchased: Bool }

struct CameraPicker: UIViewControllerRepresentable { @Binding var imageData: Data?; func makeCoordinator() -> Coordinator { Coordinator(self) }; func makeUIViewController(context: Context) -> UIImagePickerController { let picker = UIImagePickerController(); picker.sourceType = .camera; picker.delegate = context.coordinator; return picker }; func updateUIViewController(_ uiViewController: UIImagePickerController, context: Context) {} final class Coordinator: NSObject, UINavigationControllerDelegate, UIImagePickerControllerDelegate { let parent: CameraPicker; init(_ parent: CameraPicker) { self.parent = parent }; func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey: Any]) { if let image = info[.originalImage] as? UIImage { parent.imageData = image.jpegData(compressionQuality: 0.82) }; picker.dismiss(animated: true) } } }
