import SwiftUI
import PhotosUI
import HealthKit

private let green = Color(red: 0.43, green: 0.68, blue: 0.28)

struct AuthView: View {
    @EnvironmentObject private var session: SessionStore
    @State private var register = true; @State private var name = ""; @State private var email = ""; @State private var password = ""
    var body: some View { ZStack { LinearGradient(colors: [Color(red: 0.12, green: 0.25, blue: 0.18), green], startPoint: .topLeading, endPoint: .bottomTrailing).ignoresSafeArea(); ScrollView { VStack(alignment: .leading, spacing: 24) { Text("FITLY").font(.system(size: 22, weight: .bold, design: .rounded)).foregroundStyle(.white); Spacer(minLength: 100); Text(register ? "Создайте свой ритм" : "С возвращением").font(.system(size: 36, weight: .bold, design: .rounded)).foregroundStyle(.white); Text("Питание, движение и привычки в одном спокойном пространстве.").foregroundStyle(.white.opacity(0.8)); VStack(spacing: 14) { Picker("Режим", selection: $register) { Text("Регистрация").tag(true); Text("Вход").tag(false) }.pickerStyle(.segmented); if register { TextField("Имя", text: $name).textContentType(.name) }; TextField("Email", text: $email).textInputAutocapitalization(.never).keyboardType(.emailAddress); SecureField("Пароль", text: $password); if let error = session.error { Text(error).foregroundStyle(.red).font(.footnote) }; Button(register ? "Создать аккаунт" : "Войти") { Task { if register { await session.signUp(name: name, email: email, password: password) } else { await session.signIn(email: email, password: password) } } }.buttonStyle(.borderedProminent).tint(green).disabled(session.loading) }.padding(20).background(.regularMaterial, in: RoundedRectangle(cornerRadius: 24)) } .padding(24) } } }
}

struct MainTabView: View {
    var body: some View { TabView { HomeView().tabItem { Label("Главная", systemImage: "house") }; FoodView().tabItem { Label("Питание", systemImage: "fork.knife") }; ActivityView().tabItem { Label("Движение", systemImage: "figure.walk") }; RecipesView().tabItem { Label("Рецепты", systemImage: "book") }; ProfileView().tabItem { Label("Профиль", systemImage: "person") } }.tint(green) }
}

struct HomeView: View {
    @EnvironmentObject private var session: SessionStore; @State private var dashboard: Dashboard?; @State private var error: String?
    var body: some View { NavigationStack { ScrollView { VStack(alignment: .leading, spacing: 16) { Text("Добрый день, \(session.user?.name ?? "вам")").font(.title.bold()); Text(Date.now.formatted(date: .complete, time: .omitted)).foregroundStyle(.secondary); if let dashboard { MetricGrid(dashboard: dashboard) } else if error == nil { ProgressView().frame(maxWidth: .infinity) } else { EmptyState(title: "Нет данных", message: error ?? "") }; NavigationLink("Цели и привычки", destination: GoalsHabitsView()).buttonStyle(.bordered); NavigationLink("Сон и аналитика", destination: AnalyticsView()).buttonStyle(.bordered) }.padding() }.navigationTitle("FITLY").refreshable { await load() } .task { await load() } } }
    private func load() async { do { dashboard = try await session.api.request("/dashboard") } catch { error = error.localizedDescription } }
}

struct MetricGrid: View { let dashboard: Dashboard; var body: some View { LazyVGrid(columns: [GridItem(.flexible()), GridItem(.flexible())], spacing: 12) { Metric(title: "Калории", value: "\(Int(dashboard.nutrition.kcal)) ккал", icon: "flame"); Metric(title: "Белок", value: "\(Int(dashboard.nutrition.protein)) г", icon: "bolt.heart"); Metric(title: "Вода", value: "\(Int(dashboard.water)) мл", icon: "drop"); Metric(title: "Шаги", value: "\(dashboard.steps)", icon: "figure.walk") } } }
struct Metric: View { let title: String; let value: String; let icon: String; var body: some View { VStack(alignment: .leading, spacing: 8) { Image(systemName: icon).foregroundStyle(green); Text(title).font(.caption).foregroundStyle(.secondary); Text(value).font(.headline) }.frame(maxWidth: .infinity, alignment: .leading).padding().background(.thinMaterial, in: RoundedRectangle(cornerRadius: 18)) } }

struct FoodView: View {
    @EnvironmentObject private var session: SessionStore; @State private var foods: [Food] = []; @State private var meals: [Meal] = []; @State private var query = ""; @State private var amount = "250"; @State private var error: String?
    var body: some View { NavigationStack { List { Section("Сегодня") { if meals.isEmpty { EmptyState(title: "Дневник пуст", message: "Добавьте первый приём пищи") } else { ForEach(meals) { meal in VStack(alignment: .leading) { Text(meal.title).font(.headline); Text("\(Int(meal.kcal)) ккал · \(Int(meal.protein)) г белка").font(.caption).foregroundStyle(.secondary) } } .onDelete { offsets in Task { for index in offsets { try? await session.api.request("/meals/\(meals[index].id)", method: "DELETE") }; await load() } } } }; Section("Добавить продукт") { TextField("Поиск", text: $query).onSubmit { Task { await search() } }; ForEach(foods) { food in Button { Task { try? await session.api.request("/meals", method: "POST", body: MealBody(foodId: food.id, type: "snack", quantity: 1)); await load() } } label: { VStack(alignment: .leading) { Text(food.name); Text("\(Int(food.kcal)) ккал · \(food.unit)").font(.caption).foregroundStyle(.secondary) } } }; HStack { TextField("Мл воды", text: $amount).keyboardType(.numberPad); Button("+ вода") { Task { try? await session.api.request("/water", method: "POST", body: AmountBody(amount: Double(amount) ?? 250)); amount = "250" } } }; NavigationLink("AI Food Scanner", destination: FoodScannerView()) } } .navigationTitle("Питание").task { await load() }.overlay { if let error { Text(error).foregroundStyle(.red) } } } }
    private func load() async { do { let m: MealList = try await session.api.request("/meals"); meals = m.items } catch { error = error.localizedDescription } }
    private func search() async { foods = (try? await session.api.request("/foods?q=\(query.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed) ?? query)") as FoodList)?.items ?? [] }
}
private struct MealBody: Encodable { let foodId: String; let type: String; let quantity: Double }
private struct AmountBody: Encodable { let amount: Double }

struct ActivityView: View {
    @EnvironmentObject private var session: SessionStore; @State private var entries: [ActivityEntry] = []; private let health = HealthKitManager(); @State private var status = "Not connected"
    var body: some View { NavigationStack { List { Section("Сегодня") { if entries.isEmpty { EmptyState(title: "Нет активности", message: "Подключите Apple Health или добавьте вручную") } else { ForEach(entries) { Text("\($0.steps) шагов · \($0.activeMinutes) мин · \($0.source)") } } }; Section("Apple Health") { Text(status); Button("Подключить и синхронизировать") { Task { await syncHealth() } }.disabled(!health.isAvailable) } }.navigationTitle("Движение").task { await load() } } }
    private func load() async { entries = (try? await session.api.request("/activity") as ActivityList)?.items ?? [] }
    private func syncHealth() async { do { try await health.requestAuthorization(); _ = try await session.api.request("/integrations/apple-health/connect", method: "POST", body: MobileIntegrationBody(platform: "ios")) as Integration; let snapshot = try await health.readToday(); try await session.api.request("/activity", method: "POST", body: ActivityBody(steps: snapshot.steps, distance: snapshot.distance, activeMinutes: snapshot.activeMinutes, source: snapshot.source)); _ = try? await session.api.request("/integrations/apple-health/sync", method: "POST") as Integration; status = "Connected · synced now"; await load() } catch { status = error.localizedDescription } }
}
private struct ActivityBody: Encodable { let steps: Int; let distance: Double; let activeMinutes: Int; let source: String }
private struct MobileIntegrationBody: Encodable { let platform: String }

struct RecipesView: View { @EnvironmentObject private var session: SessionStore; @State private var recipes: [Recipe] = []; @State private var search = ""; var body: some View { NavigationStack { List(recipes) { recipe in HStack { if let url = recipe.image.flatMap(URL.init(string:)) { AsyncImage(url: url) { $0.resizable().scaledToFill() } placeholder: { Color.gray.opacity(0.15) }.frame(width: 64, height: 64).clipShape(RoundedRectangle(cornerRadius: 12)) }; VStack(alignment: .leading) { Text(recipe.name).font(.headline); Text("\(recipe.minutes) мин · \(Int(recipe.kcal)) ккал").font(.caption).foregroundStyle(.secondary) }; Spacer(); Button("♡") { Task { try? await session.api.request("/recipes/\(recipe.id)/favorite", method: "POST") } }.buttonStyle(.plain) } }.searchable(text: $search).task { recipes = (try? await session.api.request("/recipes") as RecipeList)?.items ?? [] }.refreshable { recipes = (try? await session.api.request("/recipes") as RecipeList)?.items ?? [] }.navigationTitle("Рецепты") } } }

struct ProfileView: View { @EnvironmentObject private var session: SessionStore; @State private var photo: PhotosPickerItem?; var body: some View { NavigationStack { List { Section { HStack { if let avatar = session.user?.avatarUrl, let url = URL(string: avatar) { AsyncImage(url: url) { $0.resizable().scaledToFill() } placeholder: { Color.gray.opacity(0.2) }.frame(width: 52, height: 52).clipShape(Circle()) } else { Image(systemName: "person.crop.circle.fill").font(.system(size: 48)).foregroundStyle(green) }; VStack(alignment: .leading) { Text(session.user?.name ?? "Профиль").font(.headline); Text(session.user?.email ?? "").foregroundStyle(.secondary).font(.caption) }; Spacer(); PhotosPicker(selection: $photo, matching: .images) { Image(systemName: "camera") }.onChange(of: photo) { item in Task { await upload(item) } } } }; Section("Разделы") { NavigationLink("Цели и привычки", destination: GoalsHabitsView()); NavigationLink("Планировщик", destination: PlannerView()); NavigationLink("Список покупок", destination: ShoppingView()); NavigationLink("FITLY AI Coach", destination: CoachView()); NavigationLink("Настройки", destination: SettingsView()); NavigationLink("Устройства", destination: DevicesView()); NavigationLink("Аналитика", destination: AnalyticsView()) }; Section { Button("Выйти", role: .destructive) { Task { await session.signOut() } } } }.navigationTitle("Профиль") } }
    private func upload(_ item: PhotosPickerItem?) async { guard let data = try? await item?.loadTransferable(type: Data.self), let data, let mime = item?.supportedContentTypes.first?.preferredMIMEType else { return }; let avatar = "data:\(mime);base64,\(data.base64EncodedString())"; guard avatar.count < 4_000_000 else { return }; do { let response: UserResponse = try await session.api.request("/profile", method: "PATCH", body: AvatarBody(avatarUrl: avatar)); session.user = response.user } catch { } }
}
private struct AvatarBody: Encodable { let avatarUrl: String }

struct GoalsHabitsView: View { @EnvironmentObject private var session: SessionStore; @State private var goals: [Goal] = []; @State private var habits: [Habit] = []; var body: some View { List { Section("Цели") { ForEach(goals) { Text("\($0.title) · \(Int($0.progressValue ?? 0))%") }; Button("Добавить цель") { Task { try? await session.api.request("/goals", method: "POST", body: TitleBody(title: "Новая цель")); await load() } } }; Section("Привычки") { ForEach(habits) { habit in Button { Task { try? await session.api.request("/habits/check", method: "POST", body: CheckBody(id: habit.id, completed: !(habit.checkedToday ?? false))); await load() } } label: { Label(habit.title, systemImage: habit.checkedToday == true ? "checkmark.circle.fill" : "circle") } }; Button("Добавить привычку") { Task { try? await session.api.request("/habits", method: "POST", body: TitleBody(title: "Новая привычка")); await load() } } } }.navigationTitle("Цели и привычки").task { await load() } }
    private func load() async { goals = (try? await session.api.request("/goals") as GoalList)?.items ?? []; habits = (try? await session.api.request("/habits") as HabitList)?.items ?? [] }
}
private struct TitleBody: Encodable { let title: String }
private struct CheckBody: Encodable { let id: String; let completed: Bool }

struct AnalyticsView: View { @EnvironmentObject private var session: SessionStore; @State private var days: [Dashboard] = []; var body: some View { List { Text("Аналитика строится по данным API. Выберите период на сайте или добавьте записи в приложении.").foregroundStyle(.secondary); NavigationLink("Сон", destination: SleepView()) }.navigationTitle("Аналитика") } }
struct SleepView: View { @EnvironmentObject private var session: SessionStore; @State private var entries: [SleepEntry] = []; @State private var durationHours = ""; var body: some View { List { ForEach(entries) { Text("\(Double($0.durationMinutes) / 60, specifier: "%.1f") ч · \($0.source)") }; Section("Ручной ввод") { TextField("Часы сна", text: $durationHours).keyboardType(.decimalPad); Button("Добавить сон") { guard let hours = Double(durationHours), hours > 0, hours <= 24 else { return }; Task { try? await session.api.request("/sleep", method: "POST", body: SleepBody(durationMinutes: Int(hours * 60), source: "manual")); durationHours = ""; await load() } }.disabled(Double(durationHours) == nil) } }.navigationTitle("Сон").task { await load() } }; private func load() async { entries = (try? await session.api.request("/sleep") as SleepList)?.items ?? [] } }
private struct SleepBody: Encodable { let durationMinutes: Int; let source: String }

struct SettingsView: View { @EnvironmentObject private var session: SessionStore; @State private var appearance: Appearance = .system; @State private var settings: Settings?; var body: some View { Form { Section("Внешний вид") { Picker("Тема", selection: $appearance) { ForEach(Appearance.allCases) { Text($0.rawValue.capitalized).tag($0) } }.onChange(of: appearance) { value in session.setAppearance(value); Task { try? await session.api.request("/settings", method: "PATCH", body: SettingsPatch(theme: value.rawValue)) } } }; Section("Уведомления") { Button("Разрешить уведомления") { Task { try? await NotificationManager.shared.requestPermission() } }; Button("Напоминание о воде") { Task { try? await NotificationManager.shared.scheduleWater() } } }; Section("Сессия") { Button("Выйти из всех данных", role: .destructive) { Task { await session.signOut() } } } }.navigationTitle("Настройки") }
}
private struct SettingsPatch: Encodable { let theme: String }
struct DevicesView: View { @EnvironmentObject private var session: SessionStore; @State private var providers: [Integration] = []; @State private var status = "Not connected"; var body: some View { List { Section("Apple Health") { Text(providers.first(where: { $0.provider == "apple-health" })?.status ?? status); Button("Открыть Activity для подключения") { status = HKHealthStore.isHealthDataAvailable() ? "Available · authorization required" : "Not available" } }; Section("Другие интеграции") { Text("Fitbit, Garmin, Health Connect и Samsung Health: Not configured").foregroundStyle(.secondary) } }.navigationTitle("Устройства").task { providers = (try? await session.api.request("/integrations") as IntegrationsResponse)?.providers ?? [] } } }
struct EmptyState: View { let title: String; let message: String; var body: some View { VStack(spacing: 8) { Image(systemName: "leaf").font(.title2).foregroundStyle(green); Text(title).font(.headline); Text(message).font(.footnote).foregroundStyle(.secondary).multilineTextAlignment(.center) }.frame(maxWidth: .infinity).padding(24) } }
