services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_USER: fitly
      MYSQL_PASSWORD: fitly
      MYSQL_ROOT_PASSWORD: fitly-root
      MYSQL_DATABASE: fitly
    ports:
      - "3306:3306"
    volumes:
      - fitly-mysql:/var/lib/mysql
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
volumes:
  fitly-mysql:
