/* global fetch, AbortController, setTimeout, clearTimeout, URLSearchParams */
import { createServer } from 'node:http'
import { randomBytes, scryptSync, timingSafeEqual, createHmac } from 'node:crypto'
import { PrismaClient } from '@prisma/client'

const port = Number(process.env.PORT || 4000)
const secret = process.env.JWT_SECRET || 'fitly-local-secret-change-me'
const prisma = process.env.DATABASE_URL ? new PrismaClient() : null
let ready = false
if (prisma) {
  for (let attempt = 1; attempt <= 5 && !ready; attempt += 1) {
    try { await prisma.$connect(); ready = true; console.log('MySQL connected') }
    catch (e) { if (attempt === 5) console.error(`MySQL unavailable: ${e.message}`); else await new Promise(resolve => setTimeout(resolve, 1500)) }
  }
}

const send = (res, status, payload) => { res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Access-Control-Allow-Origin': process.env.CORS_ORIGIN || '*', 'Access-Control-Allow-Headers': 'Content-Type, Authorization', 'Access-Control-Allow-Methods': 'GET, POST, PATCH, DELETE, OPTIONS' }); res.end(status === 204 ? '' : JSON.stringify(payload)) }
const readBody = req => new Promise(resolve => { let raw = ''; req.on('data', c => { raw += c }); req.on('end', () => { try { resolve(raw ? JSON.parse(raw) : {}) } catch { resolve(null) } }) })
const hash = (password, salt = randomBytes(16).toString('hex')) => `${salt}:${scryptSync(password, salt, 64).toString('hex')}`
const validPassword = (password, stored) => { try { const [salt, key] = String(stored).split(':'); const candidate = scryptSync(password, salt, 64).toString('hex'); return !!key && key.length === candidate.length && timingSafeEqual(Buffer.from(candidate), Buffer.from(key)) } catch { return false } }
const makeToken = id => { const payload = Buffer.from(JSON.stringify({ sub: id, exp: Date.now() + 1000 * 60 * 60 * 24 * 30 })).toString('base64url'); return `${payload}.${createHmac('sha256', secret).update(payload).digest('base64url')}` }
const getUser = async req => { if (!ready) return null; const value = req.headers.authorization || ''; if (!value.startsWith('Bearer ')) return null; const [payload, signature] = value.slice(7).split('.'); if (!payload || !signature) return null; const expected = createHmac('sha256', secret).update(payload).digest('base64url'); if (signature.length !== expected.length || !timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) return null; try { const data = JSON.parse(Buffer.from(payload, 'base64url').toString()); return data.exp > Date.now() ? prisma.user.findUnique({ where: { id: data.sub } }) : null } catch { return null } }
const userView = u => ({ id: u.id, name: u.name, email: u.email, age: u.age, goal: u.goal, units: u.units || 'metric', avatarUrl: u.avatarUrl || null, plan: 'free', createdAt: u.createdAt })
const start = v => { const d = v ? new Date(v) : new Date(); d.setHours(0, 0, 0, 0); return d }
const end = v => { const d = start(v); d.setDate(d.getDate() + 1); return d }
const mealInclude = { items: { include: { food: true } } }
const mealView = m => { const n = m.items.reduce((a, i) => ({ kcal: a.kcal + i.food.kcal * i.quantity, protein: a.protein + i.food.protein * i.quantity, fat: a.fat + i.food.fat * i.quantity, carbs: a.carbs + i.food.carbs * i.quantity, fiber: a.fiber + i.food.fiber * i.quantity }), { kcal: 0, protein: 0, fat: 0, carbs: 0, fiber: 0 }); return { ...m, title: m.items.map(i => i.food.name).join(', ') || 'Приём пищи', ...Object.fromEntries(Object.entries(n).map(([k, v]) => [k, Math.round(v * 10) / 10])) } }
const providers = ['apple-health', 'health-connect', 'fitbit', 'garmin', 'samsung-health']
const recipeImages = {
  'Зелёная шакшука': 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80',
  'Боул с лососем': 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=80',
  'Йогурт с ягодами': 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=900&q=80',
}
const notFound = (res, what) => send(res, 404, { error: `${what} not found` })

const server = createServer(async (req, res) => {
  if (req.method === 'OPTIONS') return send(res, 204, {})
  const url = new URL(req.url || '/', `http://${req.headers.host || 'localhost'}`)
  if (url.pathname === '/api/health') return send(res, 200, { status: 'ok', persistence: ready ? 'mysql' : 'unavailable' })
  if (!ready && url.pathname !== '/api/health') return send(res, 503, { error: 'MySQL is not configured or unavailable' })
  try {
    if (url.pathname === '/api/auth/register' && req.method === 'POST') { const x = await readBody(req); if (!x?.name || !x?.email || String(x.password || '').length < 8) return send(res, 400, { error: 'Имя, email и пароль от 8 символов обязательны' }); const email = String(x.email).trim().toLowerCase(); if (await prisma.user.findUnique({ where: { email } })) return send(res, 409, { error: 'Пользователь уже зарегистрирован' }); const u = await prisma.user.create({ data: { name: String(x.name).trim(), email, passwordHash: hash(String(x.password)), age: x.age ? Number(x.age) : null, goal: x.goal || 'Больше энергии', settings: { create: { notifications: {}, privacy: {} } } } }); return send(res, 201, { token: makeToken(u.id), user: userView(u) }) }
    if (url.pathname === '/api/auth/login' && req.method === 'POST') { const x = await readBody(req); const u = await prisma.user.findUnique({ where: { email: String(x?.email || '').trim().toLowerCase() } }); if (!u || !validPassword(String(x?.password || ''), u.passwordHash)) return send(res, 401, { error: 'Неверный email или пароль' }); return send(res, 200, { token: makeToken(u.id), user: userView(u) }) }
    if (url.pathname === '/api/auth/refresh' && req.method === 'POST') { const refreshed = await getUser(req); if (!refreshed) return send(res, 401, { error: 'Сессия истекла' }); return send(res, 200, { token: makeToken(refreshed.id), user: userView(refreshed) }) }
    if (url.pathname === '/api/auth/logout' && req.method === 'POST') return send(res, 200, { ok: true })
    if (url.pathname === '/api/foods' && req.method === 'GET') { const q = url.searchParams.get('q') || ''; const barcode = url.searchParams.get('barcode'); return send(res, 200, { items: await prisma.food.findMany({ where: barcode ? { barcode } : q ? { name: { contains: q, mode: 'insensitive' } } : undefined, orderBy: { name: 'asc' }, take: 100 }) }) }
    if (url.pathname === '/api/recipes' && req.method === 'GET') { const q = url.searchParams.get('q') || ''; const rows = await prisma.recipe.findMany({ where: q ? { name: { contains: q, mode: 'insensitive' } } : undefined, orderBy: { name: 'asc' } }); return send(res, 200, { items: rows.map(recipe => ({ ...recipe, image: recipeImages[recipe.name] || null, tag: Array.isArray(recipe.tags) ? recipe.tags[0] : 'FITLY' })) }) }
    const user = await getUser(req); if (!user) return send(res, 401, { error: 'Требуется авторизация' })
    if (url.pathname === '/api/foods' && req.method === 'POST') { const x = await readBody(req); if (!x?.name) return send(res, 400, { error: 'Название продукта обязательно' }); const item = await prisma.food.create({ data: { name: String(x.name).trim(), barcode: x.barcode ? String(x.barcode).trim() : null, kcal: Number(x.kcal || 0), protein: Number(x.protein || 0), fat: Number(x.fat || 0), carbs: Number(x.carbs || 0), fiber: Number(x.fiber || 0), unit: String(x.unit || 'порция') } }); return send(res, 201, { item }) }
    if (url.pathname === '/api/me' && req.method === 'GET') return send(res, 200, { user: userView(await prisma.user.findUnique({ where: { id: user.id } })) })
    if (url.pathname === '/api/profile' && req.method === 'PATCH') { const x = await readBody(req); const data = {}; for (const k of ['name', 'goal', 'units', 'age']) if (x?.[k] !== undefined) data[k] = k === 'age' ? Number(x[k]) : String(x[k]); if (x?.avatarUrl !== undefined) { const avatar = x.avatarUrl === null || x.avatarUrl === '' ? null : String(x.avatarUrl); if (avatar && (!/^data:image\/(png|jpe?g|webp|gif);base64,/i.test(avatar) || avatar.length > 4_000_000)) return send(res, 400, { error: 'Аватар должен быть изображением до 3 МБ' }); data.avatarUrl = avatar } return send(res, 200, { user: userView(await prisma.user.update({ where: { id: user.id }, data })) }) }
    if (url.pathname === '/api/settings' && req.method === 'GET') return send(res, 200, { settings: await prisma.userSettings.findUnique({ where: { userId: user.id } }) })
    if (url.pathname === '/api/settings' && req.method === 'PATCH') { const x = await readBody(req); const old = await prisma.userSettings.findUnique({ where: { userId: user.id } }); const data = { theme: x.theme ?? old?.theme ?? 'system', language: x.language ?? old?.language ?? 'ru', units: x.units ?? old?.units ?? 'metric', notifications: { ...(old?.notifications || {}), ...(x.notifications || {}) }, privacy: { ...(old?.privacy || {}), ...(x.privacy || {}) } }; return send(res, 200, { settings: await prisma.userSettings.upsert({ where: { userId: user.id }, update: data, create: { userId: user.id, ...data } }) }) }
    if (url.pathname === '/api/meals' && req.method === 'GET') { const rows = await prisma.meal.findMany({ where: { userId: user.id, date: { gte: start(url.searchParams.get('date')), lt: end(url.searchParams.get('date')) } }, include: mealInclude, orderBy: { date: 'asc' } }); return send(res, 200, { items: rows.map(mealView) }) }
    if (url.pathname === '/api/meals' && req.method === 'POST') { const x = await readBody(req); let foodId = x.foodId; if (!foodId) foodId = (await prisma.food.create({ data: { name: String(x.title || 'Новый продукт'), kcal: Number(x.kcal || 0), protein: Number(x.protein || 0), fat: Number(x.fat || 0), carbs: Number(x.carbs || 0), fiber: Number(x.fiber || 0), unit: String(x.unit || 'порция') } })).id; const m = await prisma.meal.create({ data: { userId: user.id, type: String(x.type || 'snack'), date: x.date ? new Date(x.date) : new Date(), items: { create: { foodId, quantity: Number(x.quantity || 1) } } }, include: mealInclude }); return send(res, 201, { item: mealView(m) }) }
    const mealId = url.pathname.match(/^\/api\/meals\/([^/]+)$/)?.[1]; if (mealId && req.method === 'PATCH') { const found = await prisma.meal.findFirst({ where: { id: mealId, userId: user.id } }); if (!found) return notFound(res, 'Meal'); const x = await readBody(req); return send(res, 200, { item: mealView(await prisma.meal.update({ where: { id: mealId }, data: { type: x.type ?? found.type, date: x.date ? new Date(x.date) : undefined }, include: mealInclude })) }) } if (mealId && req.method === 'DELETE') { const found = await prisma.meal.findFirst({ where: { id: mealId, userId: user.id } }); if (!found) return notFound(res, 'Meal'); await prisma.meal.delete({ where: { id: mealId } }); return send(res, 204, {}) }
    if (url.pathname === '/api/water' && req.method === 'GET') return send(res, 200, { items: await prisma.waterEntry.findMany({ where: { userId: user.id, date: { gte: start(url.searchParams.get('date')), lt: end(url.searchParams.get('date')) } }, orderBy: { date: 'desc' } }) })
    if (url.pathname === '/api/water' && req.method === 'POST') { const x = await readBody(req); return send(res, 201, { item: await prisma.waterEntry.create({ data: { userId: user.id, amount: Number(x.amount || 250), date: x.date ? new Date(x.date) : new Date() } }) }) }
    const waterId = url.pathname.match(/^\/api\/water\/([^/]+)$/)?.[1]; if (waterId && req.method === 'PATCH') { const f = await prisma.waterEntry.findFirst({ where: { id: waterId, userId: user.id } }); if (!f) return notFound(res, 'Water entry'); const x = await readBody(req); return send(res, 200, { item: await prisma.waterEntry.update({ where: { id: waterId }, data: { amount: Number(x.amount ?? f.amount) } }) }) } if (waterId && req.method === 'DELETE') { const f = await prisma.waterEntry.findFirst({ where: { id: waterId, userId: user.id } }); if (!f) return notFound(res, 'Water entry'); await prisma.waterEntry.delete({ where: { id: waterId } }); return send(res, 204, {}) }
    if (url.pathname === '/api/activity' && req.method === 'GET') return send(res, 200, { items: await prisma.activityEntry.findMany({ where: { userId: user.id }, orderBy: { date: 'desc' }, take: 200 }) })
    if (url.pathname === '/api/activity' && req.method === 'POST') { const x = await readBody(req); return send(res, 201, { item: await prisma.activityEntry.create({ data: { userId: user.id, steps: Number(x.steps || 0), distance: Number(x.distance || 0), activeMinutes: Number(x.activeMinutes || 0), type: x.type || null, duration: x.duration == null ? null : Number(x.duration), source: String(x.source || 'manual'), date: x.date ? new Date(x.date) : new Date() } }) }) }
    const activityId = url.pathname.match(/^\/api\/activity\/([^/]+)$/)?.[1]; if (activityId && (req.method === 'PATCH' || req.method === 'DELETE')) { const f = await prisma.activityEntry.findFirst({ where: { id: activityId, userId: user.id } }); if (!f) return notFound(res, 'Activity entry'); if (req.method === 'DELETE') { await prisma.activityEntry.delete({ where: { id: activityId } }); return send(res, 204, {}) } const x = await readBody(req); return send(res, 200, { item: await prisma.activityEntry.update({ where: { id: activityId }, data: { steps: x.steps == null ? f.steps : Number(x.steps), distance: x.distance == null ? f.distance : Number(x.distance), activeMinutes: x.activeMinutes == null ? f.activeMinutes : Number(x.activeMinutes), type: x.type ?? f.type, duration: x.duration == null ? f.duration : Number(x.duration) } }) }) }
    if (url.pathname === '/api/sleep' && req.method === 'GET') return send(res, 200, { items: await prisma.sleepEntry.findMany({ where: { userId: user.id }, orderBy: { date: 'desc' }, take: 200 }) })
    if (url.pathname === '/api/sleep' && req.method === 'POST') { const x = await readBody(req); return send(res, 201, { item: await prisma.sleepEntry.create({ data: { userId: user.id, durationMinutes: Number(x.durationMinutes || 0), source: String(x.source || 'manual'), date: x.date ? new Date(x.date) : new Date() } }) }) }
    const sleepId = url.pathname.match(/^\/api\/sleep\/([^/]+)$/)?.[1]; if (sleepId && (req.method === 'PATCH' || req.method === 'DELETE')) { const f = await prisma.sleepEntry.findFirst({ where: { id: sleepId, userId: user.id } }); if (!f) return notFound(res, 'Sleep entry'); if (req.method === 'DELETE') { await prisma.sleepEntry.delete({ where: { id: sleepId } }); return send(res, 204, {}) } const x = await readBody(req); return send(res, 200, { item: await prisma.sleepEntry.update({ where: { id: sleepId }, data: { durationMinutes: Number(x.durationMinutes ?? f.durationMinutes) } }) }) }
    if (url.pathname === '/api/habits' && req.method === 'GET') return send(res, 200, { items: await prisma.habit.findMany({ where: { userId: user.id, active: true }, include: { entries: { orderBy: { date: 'desc' }, take: 60 } }, orderBy: { title: 'asc' } }) })
    if (url.pathname === '/api/habits' && req.method === 'POST') { const x = await readBody(req); if (!x.title) return send(res, 400, { error: 'Название привычки обязательно' }); return send(res, 201, { item: await prisma.habit.create({ data: { userId: user.id, title: String(x.title), target: x.target || null } }) }) }
    const habitId = url.pathname.match(/^\/api\/habits\/([^/]+)$/)?.[1]; if (habitId && (req.method === 'PATCH' || req.method === 'DELETE')) { const f = await prisma.habit.findFirst({ where: { id: habitId, userId: user.id } }); if (!f) return notFound(res, 'Habit'); if (req.method === 'DELETE') { await prisma.habit.delete({ where: { id: habitId } }); return send(res, 204, {}) } const x = await readBody(req); return send(res, 200, { item: await prisma.habit.update({ where: { id: habitId }, data: { title: x.title ?? f.title, target: x.target ?? f.target, active: x.active ?? f.active } }) }) }
    if (url.pathname === '/api/habits/check' && req.method === 'POST') { const x = await readBody(req); const f = await prisma.habit.findFirst({ where: { id: x.id, userId: user.id } }); if (!f) return notFound(res, 'Habit'); const old = await prisma.habitEntry.findFirst({ where: { habitId: f.id, date: { gte: start(), lt: end() } } }); const entry = old ? await prisma.habitEntry.update({ where: { id: old.id }, data: { completed: x.completed ?? !old.completed } }) : await prisma.habitEntry.create({ data: { userId: user.id, habitId: f.id, completed: x.completed ?? true } }); return send(res, 200, { item: entry }) }
    if (url.pathname === '/api/goals' && req.method === 'GET') { const rows = await prisma.goal.findMany({ where: { userId: user.id }, include: { progress: { orderBy: { date: 'desc' }, take: 1 } } }); return send(res, 200, { items: rows.map(g => ({ ...g, progressValue: g.progress[0]?.value || 0 })) }) }
    if (url.pathname === '/api/goals' && req.method === 'POST') { const x = await readBody(req); if (!x.title) return send(res, 400, { error: 'Название цели обязательно' }); return send(res, 201, { item: await prisma.goal.create({ data: { userId: user.id, title: String(x.title), target: String(x.target || ''), type: String(x.type || 'custom'), deadline: x.deadline ? new Date(x.deadline) : null } }) }) }
    const goalId = url.pathname.match(/^\/api\/goals\/([^/]+)$/)?.[1]; if (goalId && (req.method === 'PATCH' || req.method === 'DELETE')) { const f = await prisma.goal.findFirst({ where: { id: goalId, userId: user.id } }); if (!f) return notFound(res, 'Goal'); if (req.method === 'DELETE') { await prisma.goal.delete({ where: { id: goalId } }); return send(res, 204, {}) } const x = await readBody(req); return send(res, 200, { item: await prisma.goal.update({ where: { id: goalId }, data: { title: x.title ?? f.title, target: x.target ?? f.target, type: x.type ?? f.type, status: x.status ?? f.status, deadline: x.deadline ? new Date(x.deadline) : f.deadline } }) }) }
    const fav = url.pathname.match(/^\/api\/recipes\/([^/]+)\/favorite$/)?.[1]; if (fav && (req.method === 'POST' || req.method === 'DELETE')) { if (!(await prisma.recipe.findUnique({ where: { id: fav } }))) return notFound(res, 'Recipe'); if (req.method === 'POST') await prisma.recipeFavorite.upsert({ where: { userId_recipeId: { userId: user.id, recipeId: fav } }, update: {}, create: { userId: user.id, recipeId: fav } }); else await prisma.recipeFavorite.deleteMany({ where: { userId: user.id, recipeId: fav } }); return send(res, 200, { favorite: req.method === 'POST' }) }
    if (url.pathname === '/api/favorites' && req.method === 'GET') return send(res, 200, { items: await prisma.recipeFavorite.findMany({ where: { userId: user.id }, include: { recipe: true } }) })
    if (url.pathname === '/api/meal-plans' && req.method === 'GET') return send(res, 200, { items: await prisma.mealPlan.findMany({ where: { userId: user.id }, include: { items: { include: { recipe: true, food: true } } }, orderBy: { date: 'asc' } }) })
    if (url.pathname === '/api/meal-plans' && req.method === 'POST') { const x = await readBody(req); const date = start(x.date); const p = await prisma.mealPlan.upsert({ where: { userId_date: { userId: user.id, date } }, update: {}, create: { userId: user.id, date } }); return send(res, 201, { item: await prisma.mealPlanItem.create({ data: { mealPlanId: p.id, recipeId: x.recipeId || null, foodId: x.foodId || null, type: String(x.type || 'snack') }, include: { recipe: true, food: true } }) }) }
    const planItem = url.pathname.match(/^\/api\/meal-plans\/items\/([^/]+)$/)?.[1]; if (planItem && req.method === 'DELETE') { const f = await prisma.mealPlanItem.findFirst({ where: { id: planItem, mealPlan: { userId: user.id } } }); if (!f) return notFound(res, 'Meal plan item'); await prisma.mealPlanItem.delete({ where: { id: planItem } }); return send(res, 204, {}) }
    if (url.pathname === '/api/shopping-lists' && req.method === 'GET') return send(res, 200, { items: await prisma.shoppingList.findMany({ where: { userId: user.id }, include: { items: true }, orderBy: { name: 'asc' } }) })
    if (url.pathname === '/api/shopping-lists' && req.method === 'POST') { const x = await readBody(req); return send(res, 201, { item: await prisma.shoppingList.create({ data: { userId: user.id, name: String(x.name || 'Покупки') }, include: { items: true } }) }) }
    const listId = url.pathname.match(/^\/api\/shopping-lists\/([^/]+)$/)?.[1]; if (listId && (req.method === 'PATCH' || req.method === 'DELETE')) { const f = await prisma.shoppingList.findFirst({ where: { id: listId, userId: user.id } }); if (!f) return notFound(res, 'Shopping list'); if (req.method === 'DELETE') { await prisma.shoppingList.delete({ where: { id: listId } }); return send(res, 204, {}) } const x = await readBody(req); return send(res, 200, { item: await prisma.shoppingList.update({ where: { id: listId }, data: { name: String(x.name || f.name) }, include: { items: true } }) }) }
    const shopItem = url.pathname.match(/^\/api\/shopping-lists\/([^/]+)\/items(?:\/([^/]+))?$/); if (shopItem && req.method === 'POST') { const list = await prisma.shoppingList.findFirst({ where: { id: shopItem[1], userId: user.id } }); if (!list) return notFound(res, 'Shopping list'); const x = await readBody(req); return send(res, 201, { item: await prisma.shoppingItem.create({ data: { listId: list.id, name: String(x.name || 'Товар'), quantity: Number(x.quantity || 1), unit: x.unit || null } }) }) } if (shopItem?.[2] && (req.method === 'PATCH' || req.method === 'DELETE')) { const f = await prisma.shoppingItem.findFirst({ where: { id: shopItem[2], list: { userId: user.id } } }); if (!f) return notFound(res, 'Shopping item'); if (req.method === 'DELETE') { await prisma.shoppingItem.delete({ where: { id: f.id } }); return send(res, 204, {}) } const x = await readBody(req); return send(res, 200, { item: await prisma.shoppingItem.update({ where: { id: f.id }, data: { name: x.name ?? f.name, quantity: x.quantity == null ? f.quantity : Number(x.quantity), unit: x.unit ?? f.unit, purchased: x.purchased == null ? f.purchased : Boolean(x.purchased) } }) }) }
    if (url.pathname === '/api/integrations' && req.method === 'GET') { const rows = await prisma.integration.findMany({ where: { userId: user.id } }); return send(res, 200, { providers: providers.map(provider => rows.find(r => r.provider === provider) || { provider, status: 'not_connected', lastSyncAt: null }) }) }
    const integration = url.pathname.match(/^\/api\/integrations\/([^/]+)\/(connect|disconnect|sync)$/); if (integration && req.method === 'POST') { const provider = integration[1]; const action = integration[2]; if (!providers.includes(provider)) return send(res, 400, { error: 'Unsupported provider' }); if (action === 'connect') { const x = await readBody(req); if (provider !== 'apple-health' || x?.platform !== 'ios') return send(res, 409, { error: 'Requires mobile integration or provider credentials' }); const row = await prisma.integration.upsert({ where: { userId_provider: { userId: user.id, provider } }, update: { status: 'connected', connectedAt: new Date(), metadata: { platform: 'ios', authorization: 'healthkit' } }, create: { userId: user.id, provider, status: 'connected', connectedAt: new Date(), metadata: { platform: 'ios', authorization: 'healthkit' } } }); return send(res, 200, { provider, status: row.status, connectedAt: row.connectedAt, lastSyncAt: row.lastSyncAt }) } if (action === 'disconnect') { await prisma.integration.deleteMany({ where: { userId: user.id, provider } }); return send(res, 200, { provider, status: 'not_connected' }) } const row = await prisma.integration.findFirst({ where: { userId: user.id, provider, status: 'connected' } }); if (!row) return send(res, 409, { error: 'Provider is not connected' }); const updated = await prisma.integration.update({ where: { id: row.id }, data: { lastSyncAt: new Date() } }); return send(res, 200, { provider, status: updated.status, lastSyncAt: updated.lastSyncAt }) }
    if (url.pathname === '/api/billing/plans' && req.method === 'GET') return send(res, 200, { plans: [{ id: 'free', name: 'Free', price: 0, currency: 'EUR', features: ['Дневник питания', 'Вода и активность', 'Local AI'] }, { id: 'plus', name: 'FITLY Plus', price: 799, currency: 'EUR', features: ['OpenAI Coach', 'Расширенная аналитика', 'Планы питания'] }, { id: 'pro', name: 'FITLY Pro', price: 1499, currency: 'EUR', features: ['AI Food Scanner', 'Приоритетные интеграции', 'Безлимитные планы'] }] })
    if (url.pathname === '/api/billing/subscription' && req.method === 'GET') return send(res, 200, { subscription: await prisma.subscription.findFirst({ where: { userId: user.id, status: 'active' }, orderBy: { createdAt: 'desc' } }) })
    if (url.pathname === '/api/billing/checkout' && req.method === 'POST') {
      const x = await readBody(req); const plan = String(x?.plan || ''); const prices = { plus: process.env.STRIPE_PLUS_PRICE_ID, pro: process.env.STRIPE_PRO_PRICE_ID }; if (!prices[plan]) return send(res, 503, { error: 'Платежи не настроены: добавьте Stripe price id на backend' }); if (!process.env.STRIPE_SECRET_KEY) return send(res, 503, { error: 'Платежи не настроены: добавьте STRIPE_SECRET_KEY на backend' })
      const params = new URLSearchParams({ mode: 'subscription', success_url: String(process.env.APP_URL || 'http://localhost:4173') + '?billing=success', cancel_url: String(process.env.APP_URL || 'http://localhost:4173') + '?billing=cancel', 'line_items[0][price]': prices[plan], 'line_items[0][quantity]': '1', customer_email: user.email, 'metadata[userId]': user.id, 'metadata[plan]': plan })
      const response = await fetch('https://api.stripe.com/v1/checkout/sessions', { method: 'POST', headers: { Authorization: `Bearer ${process.env.STRIPE_SECRET_KEY}`, 'Content-Type': 'application/x-www-form-urlencoded' }, body: params }); const result = await response.json(); if (!response.ok) return send(res, 502, { error: result.error?.message || 'Stripe checkout error' }); return send(res, 200, { url: result.url, sessionId: result.id })
    }
    if (url.pathname === '/api/ai/status' && req.method === 'GET') { const configured = Boolean(process.env.OPENAI_API_KEY || process.env.AI_API_KEY); return send(res, 200, { configured: configured || (process.env.AI_PROVIDER || 'local') === 'local', provider: configured ? 'openai' : 'local' }) }
    if (url.pathname === '/api/ai/food-scan' && req.method === 'POST') {
      const input = await readBody(req); const image = String(input?.image || ''); if (!image.startsWith('data:image/')) return send(res, 400, { error: 'Изображение не передано' }); const key = process.env.OPENAI_API_KEY || process.env.AI_API_KEY; if (!key) return send(res, 503, { error: 'Vision provider не настроен. Добавьте OPENAI_API_KEY.' })
      try { const response = await fetch('https://api.openai.com/v1/responses', { method: 'POST', headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ model: process.env.OPENAI_VISION_MODEL || 'gpt-4o-mini', input: [{ role: 'user', content: [{ type: 'input_text', text: 'Распознай блюдо на фото. Ответь только JSON без markdown: {"name":"...","ingredients":["..."],"portion":"...","calories":0,"protein":0,"fat":0,"carbs":0,"fiber":0,"confidence":0}. Питательность приблизительная.' }, { type: 'input_image', image_url: image, detail: 'low' }] }], max_output_tokens: 300 }) }); const result = await response.json(); if (!response.ok) return send(res, 502, { error: result.error?.message || 'Vision provider error' }); const text = result.output_text || result.output?.flatMap(item => item.content || []).map(item => item.text).filter(Boolean).join(' ') || ''; const clean = text.replace(/^```json\s*/i, '').replace(/```$/i, '').trim(); let parsed; try { parsed = JSON.parse(clean) } catch { return send(res, 502, { error: 'Vision provider вернул некорректный результат' }) } return send(res, 200, { provider: 'openai', result: parsed }) } catch (error) { return send(res, 502, { error: error.message || 'Не удалось распознать изображение' }) }
    }
    if (url.pathname === '/api/ai/coach' && req.method === 'POST') {
      const input = await readBody(req); const message = String(input?.message || '').trim(); if (!message) return send(res, 400, { error: 'Введите вопрос' })
      const today = start(); const [meals, water, activity, habits] = await Promise.all([prisma.meal.findMany({ where: { userId: user.id, date: { gte: today, lt: end() } }, include: mealInclude }), prisma.waterEntry.aggregate({ where: { userId: user.id, date: { gte: today, lt: end() } }, _sum: { amount: true } }), prisma.activityEntry.aggregate({ where: { userId: user.id, date: { gte: today, lt: end() } }, _sum: { steps: true, activeMinutes: true } }), prisma.habitEntry.count({ where: { userId: user.id, date: { gte: today, lt: end() }, completed: true } })])
      const calories = meals.reduce((sum, meal) => sum + mealView(meal).kcal, 0); const waterMl = water._sum.amount || 0; const steps = activity._sum.steps || 0; const context = `Питание сегодня: ${Math.round(calories)} ккал. Вода: ${Math.round(waterMl)} мл. Шаги: ${steps}. Выполненные привычки: ${habits}.`; const openAiKey = process.env.OPENAI_API_KEY || process.env.AI_API_KEY
      if (openAiKey) {
        try {
          const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 20000)
          const response = await fetch('https://api.openai.com/v1/responses', { method: 'POST', headers: { Authorization: `Bearer ${openAiKey}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ model: process.env.OPENAI_MODEL || 'gpt-4o-mini', input: [{ role: 'system', content: [{ type: 'input_text', text: 'Ты FITLY AI Coach. Отвечай кратко и безопасно на русском языке. Используй контекст дневника. Не ставь диагнозы, не назначай лечение, не советуй опасные ограничения питания.' }] }, { role: 'user', content: [{ type: 'input_text', text: `${context}\nВопрос пользователя: ${message}` }] }], max_output_tokens: 350 }), signal: controller.signal }); clearTimeout(timeout)
          if (response.ok) { const result = await response.json(); const text = result.output_text || result.output?.flatMap(item => item.content || []).map(item => item.text).filter(Boolean).join(' ') || ''; if (text) return send(res, 200, { provider: 'openai', message: text, context: { calories, water: waterMl, steps, habits } }) }
          console.warn('OpenAI request failed:', response.status)
        } catch (error) { console.warn('OpenAI request error:', error.message) }
      }
      const lower = message.toLowerCase(); let answer = `${context}`
      if (lower.includes('вод') || lower.includes('пить')) answer += waterMl < 1500 ? ' Попробуйте добавить стакан воды в удобное время.' : ' Гидратация сегодня уже выглядит хорошо.'
      else if (lower.includes('шаг') || lower.includes('актив')) answer += steps < 6000 ? ' Небольшая прогулка поможет мягко увеличить активность.' : ' Активность сегодня уже заметная.'
      else if (lower.includes('еда') || lower.includes('пит') || lower.includes('калор')) answer += meals.length ? ' Добавляйте продукты с учётом порции и собственных ощущений.' : ' Дневник питания пока пуст, начните с ближайшего приёма пищи.'
      else answer += ' Я могу помочь оценить дневник, воду, активность и привычки. Это общая информация, не медицинская рекомендация.'
      return send(res, 200, { provider: 'local', message: answer, context: { calories, water: waterMl, steps, habits } })
    }
    if (url.pathname === '/api/analytics' && req.method === 'GET') { const days = Math.min(90, Math.max(1, Number(url.searchParams.get('days') || 7))); const from = start(); from.setDate(from.getDate() - days + 1); const [meals, water, activity, sleep, habits] = await Promise.all([prisma.meal.findMany({ where: { userId: user.id, date: { gte: from } }, include: mealInclude }), prisma.waterEntry.findMany({ where: { userId: user.id, date: { gte: from } } }), prisma.activityEntry.findMany({ where: { userId: user.id, date: { gte: from } } }), prisma.sleepEntry.findMany({ where: { userId: user.id, date: { gte: from } } }), prisma.habitEntry.findMany({ where: { userId: user.id, date: { gte: from }, completed: true } })]); const out = Array.from({ length: days }, (_, i) => { const d = new Date(from); d.setDate(from.getDate() + i); return { date: d.toISOString().slice(0, 10), calories: 0, protein: 0, fat: 0, carbs: 0, fiber: 0, water: 0, steps: 0, activeMinutes: 0, sleepMinutes: 0, habits: 0 } }); const row = d => out.find(x => x.date === new Date(d).toISOString().slice(0, 10)); for (const m of meals) { const r = row(m.date); if (r) { const n = mealView(m); r.calories += n.kcal; r.protein += n.protein; r.fat += n.fat; r.carbs += n.carbs; r.fiber += n.fiber } } for (const x of water) { const r = row(x.date); if (r) r.water += x.amount } for (const x of activity) { const r = row(x.date); if (r) { r.steps += x.steps; r.activeMinutes += x.activeMinutes } } for (const x of sleep) { const r = row(x.date); if (r) r.sleepMinutes += x.durationMinutes } for (const x of habits) { const r = row(x.date); if (r) r.habits++ } return send(res, 200, { days: out }) }
    if (url.pathname === '/api/dashboard' && req.method === 'GET') { const today = start(); const [meals, water, activity, sleep] = await Promise.all([prisma.meal.findMany({ where: { userId: user.id, date: { gte: today, lt: end() } }, include: mealInclude }), prisma.waterEntry.aggregate({ where: { userId: user.id, date: { gte: today, lt: end() } }, _sum: { amount: true } }), prisma.activityEntry.aggregate({ where: { userId: user.id, date: { gte: today, lt: end() } }, _sum: { steps: true, activeMinutes: true } }), prisma.sleepEntry.findFirst({ where: { userId: user.id, date: { gte: today, lt: end() } }, orderBy: { date: 'desc' } })]); const n = meals.map(mealView).reduce((a, x) => ({ kcal: a.kcal + x.kcal, protein: a.protein + x.protein, fat: a.fat + x.fat, carbs: a.carbs + x.carbs, fiber: a.fiber + x.fiber }), { kcal: 0, protein: 0, fat: 0, carbs: 0, fiber: 0 }); return send(res, 200, { nutrition: n, water: water._sum.amount || 0, steps: activity._sum.steps || 0, activeMinutes: activity._sum.activeMinutes || 0, sleepMinutes: sleep?.durationMinutes || 0 }) }
    return send(res, 404, { error: 'Route not found' })
  } catch (e) { console.error(e); return send(res, 500, { error: 'Внутренняя ошибка сервера' }) }
})
server.listen(port, () => console.log(`FITLY API listening on http://localhost:${port}`))
